[transforms.pipeline_mypipeline_my_prune_0]
type = "remap"
inputs = ["input_app_in_viaq_logtype"]
source = '''
notIn = [["kubernetes","labels"],["message"],["foo"]]

# Prune keys not in `notIn` list
new_object = {}
for_each(notIn) -> |_index, pathSeg| {
    val = get(., pathSeg) ?? null
    if !is_null(val) {
        new_object = set!(new_object, pathSeg, val)
    }
}
. = new_object
'''