[transforms.pipeline_mypipeline_my_prune_0]
type = "remap"
inputs = ["input_app_in_viaq_logtype"]
source = '''
in = [["foo","test"],["bar"],["foo","@some","d.f.g.o111-22/333","foo_bar"],["foo","labels","test.dot-with/slashes888"]]

# Remove keys from `in` list
for_each(in) -> |_index, val| {
    . = remove!(., val)
}
'''