apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
  name: cluster-logging-operator-metrics-monitor
spec:
  endpoints:
  - port: http-metrics
  namespaceSelector: {}
  selector:
    matchLabels:
      control-plane: cluster-logging-operator
